#!/usr/bin/env python3
"""Normalise the corpus to schema v2 and emit corpus + indexes."""
import json, hashlib, collections, re, os

os.chdir(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------- vocabularies
CROP_MAP = {
    "winter wheat": "winter_wheat", "hard red winter wheat": "winter_wheat",
    "wheat": "wheat", "spring wheat, maize, soybeans": "spring_wheat",
    "winter barley": "winter_barley", "spring oilseed rape": "oilseed_rape",
    "oilseed rape": "oilseed_rape", "canola": "oilseed_rape",
    "maize": "maize", "rice": "rice", "boro rice": "rice",
    "potatoes": "potato", "sorghum": "sorghum", "maize and sorghum": "sorghum",
    "maize, rice": "maize", "cocoa": "cocoa", "coffee (arabica)": "coffee",
    "oranges": "orange", "mango": "mango", "livestock": "livestock",
    "wine grapes": "grapes_wine", "sugar, sugarcane": "sugar",
    "winter crops": "mixed_grains", "winter crops (wheat, barley, canola)": "mixed_grains",
    "grains (soybean, maize)": "mixed_grains", "winter cereals": "mixed_grains",
    "winter cereals, maize, sugar beet": "mixed_grains",
    "rapeseed, winter cereals": "oilseed_rape",
    "spring cereals and irrigated field crops": "spring_barley",
    "kharif crops (paddy, pulses, oilseeds, cotton)": "mixed_grains",
    "monsoon-dependent kharif crops": "mixed_grains",
    "mixed smallholder crops": "mixed_grains",
}
METRIC_MAP = {
    "production": "production", "total grain production": "production",
    "usable production forecast": "production", "crop estimate": "production",
    "production vs 5-year average": "production",
    "forward export contracts sold": "export_volume",
    "yield": "yield", "potential yield decline": "yield",
    "forecast yield anomaly": "yield", "national yield anomaly": "yield",
    "yield on irrigated land": "yield",
    "abandonment rate": "abandonment_rate",
    "condition good-to-excellent": "condition_good_excellent",
    "condition good-or-excellent": "condition_good_excellent",
    "planted area": "planted_area", "sown area": "planted_area",
    "Nov-26 futures close": "futures_price",
    "September NY cocoa futures daily change": "futures_price",
    "Thai 5% broken rice export price": "export_price",
    "on-farm irrigation reservoir fill": "reservoir_fill",
    "grain moisture at harvest": "grain_moisture",
    "seed moisture at harvest": "grain_moisture",
    "weekly average temperature anomaly": "temperature_anomaly",
    "weekly rainfall": "rainfall_mm",
    "weekly rainfall vs historical average": "rainfall_pct_normal",
    "June rainfall departure from normal": "rainfall_pct_normal",
    "March-May cumulative seasonal rainfall": "rainfall_pct_normal",
    "IMD Jun-Sep monsoon rainfall forecast": "forecast_rainfall_pct",
    "bud destruction": "crop_damage_pct", "crop damaged": "crop_damage_pct",
    "flood-damaged farmland": "damaged_area", "wheat damaged": "damaged_area",
    "deliveries vs prior-year pace": "deliveries",
}
# canonical unit per (metric) — series must not mix
CANON = {
    "condition_good_excellent": "%", "abandonment_rate": "%",
    "rainfall_pct_normal": "% of normal", "forecast_rainfall_pct": "% of LPA",
    "crop_damage_pct": "%", "reservoir_fill": "%", "grain_moisture": "%",
}
PUB_ROOT = lambda p: re.split(r"[/(]", p)[0].strip()

def norm_region(s):
    s = (s or "").lower()
    s = re.split(r"[;(,]", s)[0].strip()
    return re.sub(r"\s+", " ", s)

def series_key(r):
    # region MUST be part of the key: national and sub-national readings of the same
    # metric are different series, and two farms are not a time series at all.
    return f"{r.get('country') or 'GLOBAL'}|{norm_region(r.get('region'))}|{r['crop']}|{r.get('metric_name') or 'na'}|{PUB_ROOT(r['publisher'])}"

def claim_key(r):
    return f"{r.get('country') or 'GLOBAL'}|{r['crop']}|{r.get('season','')}|{r.get('metric_name') or 'na'}|{r.get('metric_value')}|{r.get('direction')}"

BADGE = {
    "Official": ["ahdb","usda","abares","conab","joint-research","publications.jrc","cropmonitor",
                 "gov.uk","fews.net","agriculture.gov.au","nass.usda","ers.usda","esmis.nal.usda",
                 "gov.br","eciu.net","nfuonline","coceral","munichre","abf.co.uk","lambweston",
                 "barry-callebaut","nestle","agenciagov"],
    "Trade":    ["fwi.co.uk","farminguk","graincentral","dtnpf","world-grain","potatopro",
                 "potatonewstoday","freshplaza","potatoinsights","frontierag","sucdenfinancial",
                 "barchart","cocoaintel","citrusindustry","extension.iastate","agweb","czapp",
                 "esmmagazine","admis.com","oklahomafarmreport","confectionerynews","agriland",
                 "palmoilmagazine","cropli.io","texasfarmbureau"],
}
def badge(url, publisher):
    u = (url or "").lower()
    for b, doms in BADGE.items():
        if any(d in u for d in doms): return b, None
    return "Press", "unmapped domain — defaulted to Press"

# ---------------------------------------------------------------- load & fix June
june = json.load(open("corpus/2026-06.json"))
JUNE_EVENT = {  # event_date backfill where the measurement clearly applies
    "c001":"2026-06-01","c002":"2026-06-01","c003":"2026-06","c004":"2026-06-07",
    "c005":"2026-06-28","c006":"2026-06","c007":"2026-06-11","c008":"2026-06",
    "c009":"2026-06","c010":"2026-06","c011":"2026-06","c012":"2026-06","c013":"2026-06",
    "c014":"2026-06-29","c015":"2026-06-29","c016":"2026-06-29","c017":"2026-06-26",
    "c018":"2026-06-29","c019":"2026-06-29","c020":"2026-06-28","c021":"2026-06-22",
    "c022":"2026-06","c023":"2026-06-26","c024":"2026-06-05","c025":"2026-06",
    "c030":"2026-06","c031":"2026-04","c032":"2026-06-25","c033":"2026-06",
    "c034":"2026-06","c035":"2026-06","c036":"2026-06","c037":"2026-06","c038":"2026-06-28",
    "c039":"2026-06","c040":"2026-06","c041":"2026-06-24","c042":"2026-06","c044":"2026-06-05",
    "c045":"2026-06","c047":"2026-06","c048":"2026-06","c049":"2026-05","c051":"2026-06",
    "c054":"2026-06","c055":"2026-06","c056":"2026-06-25",
}
for r in june:
    r["crop"] = CROP_MAP.get(r["crop"], r["crop"])
    if r.get("metric_name"):
        r["metric_name"] = METRIC_MAP.get(r["metric_name"], r["metric_name"])
        if r["metric_name"] in CANON: r["metric_unit"] = CANON[r["metric_name"]]
    if r["id"] in JUNE_EVENT: r["event_date"] = JUNE_EVENT[r["id"]]
    r["month"] = "2026-06"

# ---------------------------------------------------------------- July / August
def R(cid,country,region,crop,season,hz,ic,qt,metric,val,unit,dirn,base,ev,title,url,pub,pd,quote,attr,corr=0,comp=None,flag=None):
    return {"id":cid,"country":country,"region":region,"crop":crop,"season":season,
            "hazard_type":hz,"impact_class":ic,"is_quantified":qt,"metric_name":metric,
            "metric_value":val,"metric_unit":CANON.get(metric,unit),"direction":dirn,"baseline":base,
            "event_date":ev,"title":title,"url":url,"publisher":pub,"published_date":pd,
            "verbatim_quote":quote,"attribution":attr,"corroboration_count":corr or 1,
            "companies":comp or [],"review_flag":flag,"corroborations":[],
            "summary":title}

JUL = [
R("j001","EU","EU-27","maize","2026","heat","yield",True,"yield",-6.5,"%","down","previous MARS forecast","2026-07","EU grain maize and sunflower yield forecasts cut 6-7% after repeated heatwaves","https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/heatwaves-impact-summer-and-winter-crops-2026-07-27_en","European Commission JRC (MARS)","2026-07-27","Yield forecasts have been reduced for all spring and summer crops, most notably for grain maize and sunflowers (6–7 %).","weather_explicit",3),
R("j002","EU","EU-27","mixed_grains","2026","heat","yield",True,"yield",-1,"% vs 5-yr avg","down","five-year average","2026-07","EU winter crop yields revised down 1-4%; total cereals 1% below five-year average","https://joint-research-centre.ec.europa.eu/jrc-news-and-updates/heatwaves-impact-summer-and-winter-crops-2026-07-27_en","European Commission JRC (MARS)","2026-07-27","EU yield forecasts for winter crops have been revised downwards by 1–4 %, leaving the outlook for total cereals at 1 % below the five-year average.","weather_explicit",2),
R("j003","EU","Europe","mixed_grains","2026","heat","economy_macro",True,"revenue",-2000,"EUR million","down","pre-heatwave June forecast","2026-06","June heatwave knocks EUR 2 billion off European harvest prospects","https://eciu.net/media/press-releases/june-heatwave-knocks-2-billion-off-european-harvest-prospects-new-analysis","ECIU","2026-07-22","the June heatwave is likely to have cost European grain farmers around €2 billion in lost revenue","weather_explicit",2),
R("j004","EU","EU-27 + UK","mixed_grains","2026","heat","yield",True,"production",-9,"million tonnes","down","June 2026 forecast","2026-06","European harvest forecast 9 million tonnes smaller than expected in June","https://eciu.net/media/press-releases/june-heatwave-knocks-2-billion-off-european-harvest-prospects-new-analysis","ECIU","2026-07-22","the European harvest is now forecast to be 9 million tonnes smaller than expected in June","weather_explicit"),
R("j005","FR","France","maize","2026","heat","yield",True,"production",-3.4,"million tonnes","down","June 2026 forecast","2026-06","French maize production forecast cut by 3.4 million tonnes; grain losses worth EUR 891m","https://eciu.net/media/press-releases/june-heatwave-knocks-2-billion-off-european-harvest-prospects-new-analysis","ECIU","2026-07-22","The biggest reductions in forecast production are in France, where the maize crop is expected to be 3.4m tonnes less","weather_explicit"),
R("j006","EU","EU-27 + UK","maize","2026/27","heat","yield",True,"production",52.7,"million tonnes","down","57.2 Mt June forecast; 57.4 Mt in 2025","2026-07","COCERAL cuts EU maize forecast to 52.7 Mt in extraordinary out-of-cycle release","https://ukragroconsult.com/en/news/coceral-cuts-eu-grain-crop-forecast-due-to-extreme-heat/","COCERAL","2026-07-13","The corn outlook was revised even more sharply, with production now estimated at 52.7 mln tons, down from 57.2 mln tons in the previous forecast and 57.4 mln tons last year.","weather_explicit",2),
R("j007","EU","EU-27","wheat","2026/27","heat","yield",True,"production",140.8,"million tonnes","down","143.7 Mt prior; 149.8 Mt in 2025","2026-07","COCERAL cuts EU soft wheat forecast to 140.8 Mt","https://ukragroconsult.com/en/news/coceral-cuts-eu-grain-crop-forecast-due-to-extreme-heat/","COCERAL","2026-07-13","The soft wheat crop forecast was reduced to 140.8 mln tons, compared with 143.7 mln tons in the previous estimate and 149.8 mln tons harvested in 2025.","weather_explicit"),
R("j008","FR","France","maize","2026","heat","yield",True,"condition_good_excellent",38,"%","down","40% a week earlier; 69% a year ago","2026-07-20","French maize rated 38% good or excellent by 20 July, against 69% a year earlier","https://ahdb.org.uk/news/arable-market-report-27-july-2026","AHDB","2026-07-27","FranceAgriMer reporting that just 38% of the maize area was in good or excellent condition by 20 July, down from 40% a week earlier and 69% a year ago.","weather_explicit"),
R("j009","FR","France","maize","2026","heat","yield",True,"condition_good_excellent",58,"%","down","76% previous week; lowest since 2013","2026-06-29","French maize ratings plunge to 13-year low at 58% good/excellent","https://www.esmmagazine.com/supply-chain/french-maize-crop-ratings-plunge-to-13-year-low-in-heatwave-315745","ESM Magazine","2026-07-06","The share of the grain maize crop in good/excellent condition had fallen to 58% by June 29 from 76% the previous week","weather_explicit"),
R("j010","FR","France","wheat","2026","heat","yield",True,"production",30.8,"million tonnes","down","2025 production (-7.6%)","2026-07","Argus field survey puts French soft wheat at 30.80 Mt, down 7.6% on 2025","https://www.brecorder.com/news/amp/40430882","Reuters / Business Recorder","2026-07-20","France's soft wheat crop is expected to fall to 30.80 million metric tons this year, down 7.6% from 2025","weather_explicit"),
R("j011","FR","France","wheat","2026","heat","yield",True,"yield",6.67,"t/ha","down","10-year Olympic average (-6.5%)","2026-07","Argus estimates French soft wheat yield at 6.67 t/ha, 6.5% below the 10-year average","https://www.brecorder.com/news/amp/40430882","Reuters / Business Recorder","2026-07-20","Argus estimated the French soft wheat yield at 6.67 tons per hectare, 6.5% below the 10-year Olympic average","weather_explicit"),
R("j012","FR","France","maize","2026","drought","yield",True,"production",8.9,"million tonnes","down","one-third below 2025","2026-07","Expana projects French maize at 8.9 Mt, a third below 2025, as farmers fear a repeat of 1976","https://finance.yahoo.com/markets/commodities/articles/wilting-french-maize-shrink-europes-122259321.html","Reuters","2026-07-10","8.9 million metric tons, one-third below last year's level","weather_explicit"),
R("j013","FR","France / EU","sugar","2026/27","drought","price_market",True,"production",14.13,"million tonnes","down","down 15% from 2025/26","2026-07","Drought threatens French sugar beet; EU 2026/27 sugar output pegged at 14.13 Mt, down 15%","https://www.esmmagazine.com/supply-chain/drought-threatens-french-sugar-beet-crop-with-no-rain-in-sight-315484","ESM Magazine","2026-07-01","the European Commission pegged EU sugar output in 2026/27 at 14.13 million metric tonnes, down 15% from 2025/26","weather_explicit"),
R("j014","DE","Germany","winter_wheat","2026","heat","yield",True,"production",22.57,"million tonnes","down","2025 harvest (-11.7%)","2026-07","German winter wheat forecast cut to 22.57 Mt, down 11.7%, after heat cut grain numbers and size","https://ukragroconsult.com/en/news/germany-to-lose-1-4-mln-tons-of-grain-due-to-heatwave/","Deutscher Raiffeisenverband","2026-07-17","Winter wheat production is forecast at 22.57 mln tons, down 11.7% year-on-year.","weather_explicit",0,None,"syndicated via aggregator; original is DRV"),
R("j015","US","Great Plains","winter_wheat","2026","drought","yield",True,"production",990,"million bushels","down","down 29% from 2025","2026-07-01","USDA cuts US winter wheat to 990 million bushels, down 29% year on year","https://esmis.nal.usda.gov/sites/default/release-files/795973/crop0726.pdf","USDA NASS","2026-07-10","Winter wheat production is forecast at 990 million bushels, down 4 percent from the June 1 forecast and down 29 percent from 2025.","weather_explicit"),
R("j016","US","United States","winter_wheat","2026","drought","yield",True,"yield",46.7,"bu/acre","down","54.9 bu/acre in 2025; lowest since 2015","2026-07-01","US winter wheat yield forecast at 46.7 bu/acre, lowest since 2015","https://esmis.nal.usda.gov/sites/default/release-files/795973/crop0726.pdf","USDA NASS","2026-07-10","As of July 1, the United States yield is forecast at 46.7 bushels per acre, down 0.1 bushel from last month and down 8.2 bushels from last year's average yield of 54.9 bushels per acre.","weather_explicit"),
R("j017","US","Nebraska","winter_wheat","2026","drought","yield",True,"condition_good_excellent",93,"% very poor to poor","down","state ratings, late June 2026","2026-06","Nebraska winter wheat 93% very poor to poor; rangeland 66% very poor to poor","https://esmis.nal.usda.gov/sites/default/release-files/795973/crop0726.pdf","USDA NASS","2026-07-10","93 percent very poor to poor","weather_explicit",0,None,"metric is very-poor-to-poor, not good-to-excellent — inverse of the series"),
R("j018","US","Corn Belt and Plains","maize","2026","heat","yield",True,"condition_good_excellent",63,"%","down","67% previous week; 73% year earlier","2026-07-26","US corn falls to 63% good-to-excellent, biggest late-July weekly drop in nearly two decades","https://www.dtnpf.com/agriculture/web/ag/news/article/2026/07/27/usda-crop-progress-corn-rated-63-63","DTN/Progressive Farmer","2026-07-27","NASS estimated that 63% of the crop was in good-to-excellent condition, 4 percentage points below the previous week of 67% and 10 percentage points below last year's 73%.","weather_explicit",3),
R("j019","US","Northern Plains","spring_wheat","2026","heat","yield",True,"condition_good_excellent",58,"%","down","76% same week prior year","2026-07-12","US spring wheat at 58% good-to-excellent, 18 points behind prior year","https://www.dtnpf.com/agriculture/web/ag/news/article/2026/07/13/usda-crop-progress-corn-rated-68-65","DTN/Progressive Farmer","2026-07-13","4 points behind last year's pace of 76%","weather_explicit"),
R("j020","US","Kansas (Sherman, Marshall counties)","winter_wheat","2026","drought","yield",True,"yield",21,"bu/acre","down","normal county yields","2026-07","Kansas wheat harvest yields 7-35 bu/acre in Sherman County after drought, freeze and hail","https://www.oklahomafarmreport.com/2026/07/03/2026-kansas-wheat-harvest-nears-completion-amid-highly-variable-yields-and-weather-challenges/","Oklahoma Farm Report","2026-07-03","drought, freeze damage and hail led to highly variable yields","weather_explicit"),
R("j021","GB","United Kingdom","winter_wheat","2026 harvest","drought","yield",True,"yield",6.8,"t/ha","down","UK five-year average (-13%)","2026-07-26","AHDB first harvest report: winter wheat 6.8 t/ha, 13% below five-year average, 90% of farms below their own average","https://www.fwi.co.uk/arable/harvest/report-shows-wheat-yields-below-average-on-90-of-farms","AHDB / Farmers Weekly","2026-07-31","Based on the survey sample, the average yield is 6.8 t/ha, down 13% compared to the UK five-year average.","weather_explicit",3),
R("j022","GB","United Kingdom","oilseed_rape","2026 harvest","favourable","yield",True,"yield",3.9,"t/ha","up","UK five-year average (+17%)","2026-07-26","POSITIVE: UK oilseed rape 3.9 t/ha, 17% above the five-year average","https://www.fwi.co.uk/arable/harvest/report-shows-wheat-yields-below-average-on-90-of-farms","AHDB / Farmers Weekly","2026-07-31","The average oilseed rape yield from the survey is 3.9 t/ha, up 17% compared to the UK five-year average.","weather_explicit",3),
R("j023","GB","United Kingdom","winter_barley","2026 harvest","drought","yield",True,"yield",6.8,"t/ha","down","UK five-year average (-2%)","2026-07-26","UK winter barley 6.8 t/ha, only 2% below average, largely cut before the worst of the drought","https://www.fwi.co.uk/arable/harvest/report-shows-wheat-yields-below-average-on-90-of-farms","AHDB / Farmers Weekly","2026-07-31","Based on the survey sample, the average yield is 6.8t/ha, 2% lower than the UK five-year average.","weather_explicit"),
R("j024","GB","England","mixed_grains","2026","drought","farmer_livelihood",True,"rainfall_pct_normal",7,"% of normal","down","long-term July average","2026-07","England receives just 7% of average July rainfall, on track for driest July since 1836","https://www.gov.uk/government/publications/dry-weather-and-drought-in-england-2026-summary-reports/dry-weather-and-drought-in-england-24-to-30-july-2026","Environment Agency / Defra","2026-07-31","For England as a whole, the total for the month so far is just 7% of the LTA","weather_explicit",2),
R("j025","GB","England","mixed_grains","2026","drought","farmer_livelihood",True,"reservoir_fill",72,"%","down","9.5% below long-term average","2026-07-30","English reservoir storage falls to 72%; seven areas move to drought status","https://www.gov.uk/government/publications/dry-weather-and-drought-in-england-2026-summary-reports/dry-weather-and-drought-in-england-24-to-30-july-2026","Environment Agency / Defra","2026-07-31","National storage is 72%, which is 9.5% below the LTA","weather_explicit",2),
R("j026","GB","England","mixed_grains","2026","drought","farmer_livelihood",True,"reservoir_fill",75.3,"%","down","7.4% below long-term average","2026-07-21","English reservoir storage at 75.3%; livestock farmers begin using winter forage reserves","https://www.gov.uk/government/publications/dry-weather-and-drought-in-england-2026-summary-reports/dry-weather-and-drought-in-england-17-to-23-july-2026","Environment Agency / Defra","2026-07-24","Livestock farmers have already begun using their winter forage reserves because the dry weather has impacted on grass growth.","weather_explicit"),
R("j027","GB","England","spring_barley","2026","drought","yield",True,"rainfall_pct_normal",3,"% of normal","down","July LTA to 16 July","2026-07-16","England at 3% of average July rainfall to 16 July; spring barley yields expected to be hit","https://www.gov.uk/government/publications/dry-weather-and-drought-in-england-2026-summary-reports/dry-weather-and-drought-in-england-10-july-to-16-july-2026","Environment Agency / Defra","2026-07-17","July has continued to be very dry with only 3% of the long term average (LTA) rainfall received.","weather_explicit"),
R("j028","GB","England (East Anglia and others)","mixed_grains","2026","drought","farmer_livelihood",True,"damaged_area",1506,"abstraction restrictions","up","normal season","2026-07-29","NFU reports 1,506 abstraction licence restrictions; East Anglian irrigators forced to stop taking river water","https://www.nfuonline.com/news/national-drought-group-update/","NFU","2026-07-29","1,506 abstraction licence restrictions","weather_explicit"),
R("j029","GB","South West England (Torpoint, Devon)","potato","2026","drought","yield",True,"yield",82.5,"% of normal","down","normal yield","2026-07","Devon grower Jeremy Oatey reports crisping potato yields at 80-85% of normal across 242ha","https://www.fwi.co.uk/business/markets-and-trends/crop-prices/potatoes-show-signs-of-stress-as-drought-strikes","Farmers Weekly","2026-07-30","Devonshire grower Jeremy Oatey who grows 242ha of potatoes at Hay Farm near Torpoint, has started lifting potatoes for crisping and reports yields at about 80-85% of \"normal\".","weather_explicit"),
R("j030","GB","Great Britain","dairy","2026","heat","yield",True,"production",-18.5,"million litres","down","pre-heatwave production","2026-06","AHDB estimates GB milk production down 18.5 million litres after May and June heatwaves","https://www.indexbox.io/blog/heatwaves-disrupt-gb-milk-production-causing-short-term-undersupply/","AHDB (via IndexBox)","2026-07-13","GB milk production is estimated to have fallen by 18.5 million litres so far due to the heatwaves","weather_explicit",2,None,"secondary source citing AHDB"),
R("j031","BE","NW Europe (BE, NL, FR, DE)","potato","2026","heat","farmer_livelihood",True,"planted_area",536900,"hectares","down","604,100 ha in 2025 (-11%)","2026-07","NEPG: NW European ware potato area falls 11% to 536,900 ha; Belgium -16.6%, Netherlands -15.1%","https://www.potatopro.com/news/2026/north-western-european-potato-growers-nepg-european-ware-potato-area-falls-11-growers-cut","NEPG","2026-07-05","the total ware potato area is expected to fall from 604,100 hectares in 2025 to approximately 536,900 hectares in 2026, representing a reduction of around 67,000 hectares","implied",2,None,"primarily price-driven; heat is a secondary risk factor"),
R("j032","NL","Netherlands, Belgium, Poland","potato","2026","heat","yield",True,"yield",43.3,"t/ha","down","2025 yields (-6%)","2026-06","JRC MARS cuts potato yield expectations 6% in the Netherlands, 5% Belgium, 7% Poland","https://potatoinsights.com/european-heatwave-raises-concerns-for-potato-farmers/","Potato Insights","2026-07-05","Current JRC MARS forecasts already show yield expectations down 6% in the Netherlands, 5% in Belgium and 7% in Poland compared to 2025.","weather_explicit"),
R("j033","BR","Mato Grosso; Goiás, Minas Gerais, Piauí","soybean","2025/26","favourable","yield",True,"production",180.6,"million tonnes","up","previous season (+5.3%)","2026-07","POSITIVE: CONAB raises Brazil soybeans to 180.6 Mt; total grain a record 360.1 Mt","https://agenciagov.ebc.com.br/noticias/202607/producao-de-graos-e-estimada-em-360-1-milhoes-de-toneladas-no-ciclo-2025-2026","CONAB","2026-07-14","a soja alcança uma produção de 180,6 milhões de toneladas, avanço de 5,3%","weather_explicit"),
R("j034","BR","Minas Gerais, Espírito Santo, Rondônia","coffee","2026/27","drought","yield",True,"production",-17.5,"%","down","CONAB forecast of 66.7 million bags","2026-07","Abic warns El Niño could cut Brazil's coffee crop 15-20% from 66.7 million bags","https://www.bnnbloomberg.ca/investing/commodities/2026/07/13/brazil-coffee-faces-el-nino-headwinds-but-crops-more-resilient/","Bloomberg","2026-07-13","We are now talking about a crop loss of 15 per cent to 20 per cent, which in a normal year would be within expectations.","enso_explicit",2),
R("j035","CI","Côte d'Ivoire and Ghana","cocoa","2026/27","flood","yield",True,"production",1.75,"million tonnes","down","nearly 2.2 Mt expected in 2025/26","2026-07","Ivorian cocoa output seen falling to 1.7-1.8 Mt as El Niño fears push cocoa to six-month highs","https://www.ecofinagency.com/news-agriculture/1007-57272-el-nino-pushes-cocoa-prices-higher-as-west-africa-supply-risks-return","Ecofin Agency","2026-07-10","Côte d'Ivoire's cocoa output could fall to between 1.7 million and 1.8 million tonnes, compared with nearly 2.2 million tonnes expected during the 2025/2026 season","enso_explicit",2),
R("j036","CI","Côte d'Ivoire","cocoa","2026/27","flood","yield",True,"production",-10,"%","down","1.6 Mt current season","2026-07","Ivorian pod counters expect 2026/27 main crop down over 10% after excess rains and black pod disease","https://www.cnbcafrica.com/2026/ivory-coast-2026-27-cocoa-crop-to-drop-more-than-10-amid-excess-rains-disease-counters-say","Reuters via CNBC Africa","2026-07-10","We are very worried (about El Nino) because the impact would be enormous.","enso_explicit"),
R("j037","IN","All-India (Gangetic plains)","rice","kharif 2026","drought","food_security",True,"planted_area",11.47,"million hectares","down","12.55 million ha same date 2025","2026-07-10","Paddy sown on 11.47 million ha by 10 July, 1.08 million ha below last year; 397 of 741 districts rainfall-deficient","https://www.downtoearth.org.in/agriculture/kharif-crop-in-trouble-rainfall-deficit-hits-397-districts-as-paddy-growing-areas-along-the-ganga-face-drought-like-conditions","Down To Earth","2026-07-14","Paddy had been sown on 11.47 million hectares as of July 10, 2026. This is 1.08 million hectares lower than the 12.55 million hectares recorded during the same period last year.","weather_explicit",2),
R("j038","IN","All-India","mixed_grains","kharif 2026","drought","yield",True,"planted_area",78.7,"million hectares","down","82.6 million ha a year earlier","2026-07-24","Monsoon revival narrows India's deficit to 16%, but summer-sown area still 78.7 million ha vs 82.6 million","https://www.brecorder.com/news/40432192/indias-summer-crop-planting-gathers-pace-as-monsoon-revives","Reuters / Business Recorder","2026-07-28","78.7 million hectares as of July 24, compared with 82.6 million hectares a year earlier","weather_explicit"),
R("j039","IN","All-India","maize","kharif 2026","drought","yield",True,"planted_area",7.8,"million hectares","down","same period last year (-9.7%)","2026-07-24","Indian maize planted area down 9.7% to 7.8 million ha, sharpest fall among major kharif crops","https://www.brecorder.com/news/40432192/indias-summer-crop-planting-gathers-pace-as-monsoon-revives","Reuters / Business Recorder","2026-07-28","7.8 million hectares down 9.7% from the same period last year","weather_explicit"),
R("j040","MY","Malaysia (Negeri Sembilan, Johor, Pahang, Sabah)","palm_oil","2026","drought","price_market",True,"production",-3,"% y/y","down","2025 output","2026-07","MPOB projects 2-4% fall in Malaysian palm oil output from Q4 as El Niño peaks","https://www.thestar.com.my/business/business-news/2026/07/28/el-nino-onset-to-drive-cpo-price-trajectory","The Star (Malaysia)","2026-07-28","10% to 14% decline in fresh fruit bunch yields","enso_explicit"),
R("j041","ID","Sumatra and Kalimantan","palm_oil","2026","drought","yield",True,"rainfall_pct_normal",86.08,"% of normal","down","normal rainfall","2026-08","BMKG: 86% of Indonesia forecast below-normal rainfall in August, rising to 87.6% in September","https://www.palmoilmagazine.com/hot-news/2026/07/26/bmkg-warns-el-nino-to-keep-indonesias-palm-oil-regions-drier-until-october-2026/","Palm Oil Magazine","2026-07-25","Approximately 86.08% of the country is forecast to experience below-normal rainfall in August, increasing to 87.61% in September before easing slightly to 81.24% in October.","enso_explicit",2),
R("j042","VN","Vietnam (central region)","rice","2026","drought","food_security",True,"damaged_area",350000,"hectares at risk","up","no El Niño impact","2026-07","Vietnam warns severe El Niño may affect rice across 350,000 hectares; Thai prices at 18-month high","https://bworldonline.com/bloomberg/2026/07/27/766175/el-nino-worsens-plight-of-asias-rice-belt-after-war-price-shock/","Bloomberg","2026-07-27","Vietnam warns severe El Niño may affect rice crops across 350,000 hectares","enso_explicit"),
R("j043","LS","Lesotho","potato","2025/26","flood","food_security",True,"crop_damage_pct",40,"%","down","national potato and bean crop","2026-06","GEOGLAM: 30-50% of Lesotho potato and bean crops lost to waterlogging and flooding","https://www.cropmonitor.org/crop-monitor-for-early-warning-202607","GEOGLAM Crop Monitor","2026-07-02","30 to 50 percent of potato and bean crops, 20 to 30 percent of maize crops, and 10 percent of sorghum crops have been lost","weather_explicit"),
R("j044","SY","Syria (Euphrates governorates)","wheat","2026","flood","food_security",True,"damaged_area",85,"% of irrigation systems","down","irrigation systems in affected areas","2026-06","GEOGLAM: an estimated 85% of irrigation systems non-functional in flood-affected Syrian areas","https://www.cropmonitor.org/crop-monitor-for-early-warning-202607","GEOGLAM Crop Monitor","2026-07-02","An estimated 85 percent of irrigation systems were reported as nonfunctional in affected areas","weather_explicit"),
R("j045","KE","Western Kenya and North Rift","maize","2026","drought","food_security",True,"rainfall_pct_normal",45,"% of normal","down","seasonal average","2026-06","GEOGLAM downgrades Kenya to watch; western Kenya rainfall 30-60% of average under El Niño","https://www.cropmonitor.org/crop-monitor-for-early-warning-202607","GEOGLAM Crop Monitor","2026-07-02","rainfall totals are less than 30 to 60 percent of average","enso_explicit"),
R("j046","BD","Chattogram, Noakhali, Cumilla, Barishal","rice","2026","flood","yield",True,"damaged_area",24138,"hectares","down","n/a","2026-07","Bangladesh monsoon rains damage 1.34 lakh tonnes of crops across 24,138 hectares","https://asianews.network/rain-floods-damage-crops-worth-usd-38-82-million-in-bangladesh/","The Daily Star","2026-07-28","More than 1.34 lakh tonnes of crops worth around Tk 478 crore were damaged across 24,138 hectares of farmland","weather_explicit"),
R("j047","ZW","Zimbabwe (deficit districts)","maize","2026","drought","price_market",True,"spot_price",0.57,"USD/kg","up","0.22 USD/kg in surplus areas","2026-07","FEWS NET: Zimbabwe maize prices 0.34-0.57 USD/kg in deficit districts against 0.22 in surplus areas","https://fews.net/southern-africa/zimbabwe/key-message-update/july-2026","FEWS NET","2026-07-31","Low supply is driving above-average maize grain prices, ranging between 0.34-0.57 USD/kilogram","enso_explicit"),
R("j048","AU","Western Australia","mixed_grains","2026-27","drought","yield",True,"production",22.7,"million tonnes","down","27.3 Mt record in 2025","2026-07","GIWA forecasts a 22.7 Mt Western Australian crop with 20% variability; drier, hotter spring signal strengthening","https://www.graincentral.com/news/giwa-sees-22-7mt-crop-with-20pc-variability-on-increased-area/","GIWA","2026-07-17","most regions that are currently in good shape will need to receive another 50mm of rain and the areas that experienced a later start will need another 100mm of rain","weather_explicit"),
R("j049","AU","Queensland, NSW, Victoria, SA","barley","2026-27","drought","price_market",True,"spot_price",400,"AUD/tonne","up","A$390/t previous week","2026-07-23","Dry week lifts Australian feedgrain prices; Downs barley to A$400/t","https://www.graincentral.com/markets/feedgrain-focus-prices-keep-kicking-growers-hold-in-dry-week/","Grain Central","2026-07-23","Cropping regions in Queensland and New South Wales recorded little to no rain in the past week.","weather_explicit"),
R("j050","GB","UK, Spain, southern Africa","sugar","2026","heat","company_corporate",True,"revenue",-60,"GBP million","down","FY2026 guidance","2026-07-01","ABF guides Sugar to a GBP 25-60m adjusted operating loss, citing unseasonal weather","https://www.abf.co.uk/content/dam/abf/corporate/Documents/investors/results-and-presentations/2026/abf-trading-update-july-2026.pdf.downloadasset.pdf","Associated British Foods","2026-07-01","Taking these factors together, we now expect Sugar to deliver an adjusted operating loss in the range of GBP25 million to GBP60 million in the 2026 financial year.","implied",0,["Associated British Foods","British Sugar"]),
R("j051","US","Pacific Northwest and Europe","potato","2026","favourable","company_corporate",True,"cost",33.1,"USD million","up","FY26 International segment","2026-07-24","POSITIVE: Lamb Weston says NA and EU potato crop years off to a favourable start; takes $33.1m potato write-off","https://investors.lambweston.com/news-releases/news-release-details/lamb-weston-announces-q4-and-full-year-fiscal-2026-results","Lamb Weston","2026-07-24","In North America, the crop year is off to a strong start with favorable weather and crop development slightly ahead of historical timing.","weather_explicit",0,["Lamb Weston"]),
R("j052","CH","West Africa, Ecuador","cocoa","2025/26","favourable","company_corporate",True,"spot_price",-47,"%","down","prior-year period","2026-07-09","Barry Callebaut reports average cocoa bean prices down 47%; strong West African main crop arrivals","https://www.barry-callebaut.com/en/about-us/media/news-stories/barry-callebaut-group-9-month-key-sales-figures-fiscal-year-202526","Barry Callebaut","2026-07-09","On average, cocoa bean prices decreased by -47% versus the prior-year period and closed the period at GBP 2,954","implied",0,["Barry Callebaut"]),
R("j053","CH","Global","cocoa","H1 2026","drought","company_corporate",True,"revenue",4.3,"% organic growth","down","11.2% in H1 2025","2026-07-21","Lindt growth slows to 4.3% as cocoa-cost-driven price rises weigh on volumes","https://www.confectionerynews.com/Article/2026/07/21/lindt-growth-slows-as-cocoa-costs-continue-to-weigh-on-volumes/","ConfectioneryNews","2026-07-21","Lindt reports 4.3% organic growth in H1 2026","implied",0,["Lindt & Sprüngli"]),
R("j054","US","Europe, West Africa","cocoa","2026","heat","company_corporate",True,"production",0.5,"million tonnes surplus","up","2026 supply-demand balance","2026-07-28","Mondelez flags historically high cocoa surplus and notes an unusual heatwave hurt European chocolate consumption","https://www.investing.com/news/transcripts/earnings-call-transcript-mondelez-beats-q2-2026-estimates-lifts-sales-outlook-93CH-4818297","Mondelez (via Investing.com)","2026-07-28","The surplus between demand and supply in cocoa is at historical high. I think for this year, we are going to have at least half a million metric tons of surplus.","weather_explicit",0,["Mondelez International"]),
R("j055","DE","Global","mixed_grains","H1 2026","drought","economy_macro",True,"cost",44,"USD billion","down","H1 average","2026-07-30","Munich Re puts H1 insured natural catastrophe losses at $44bn, flagging weak Indian monsoon and El Niño drought risk","https://www.munichre.com/en/company/media-relations/media-information-and-corporate-news/media-information/2026/natural-disaster-figures-first-half-2026.html","Munich Re","2026-07-30","In many regions - such as Australia, Central America and southwestern Africa - El Nino is increasing the risk of drought and wildfires.","enso_explicit",0,["Munich Re"]),
R("j056","BR","Southern Minas Gerais, Mogiana, Paraná","coffee","2026/27","frost","price_market",True,"futures_price",16,"% daily move","up","pre-frost-scare level","2026-07","Frost forecasts trigger coffee rally: NY arabica up over 16%, London robusta nearly 9%","https://www.cocoaintel.com/frost-concerns-trigger-sharp-rally-as-supply-fundamentals-remain-in-focus-6-july-2/","CocoaIntel","2026-07-07","Arabica contracts in New York surging more than 16% and Robusta futures in London gaining nearly 9%","weather_explicit",0,None,"unmapped domain"),
R("j057","GR","Evros, north-eastern Greece","cotton","2026","storm","farmer_livelihood",False,None,None,None,"down",None,"2026-07","Hail and windstorm devastate cotton, maize and walnut orchards around Alexandroupoli","https://athens-times.com/alexandroupoli-hit-by-hail-and-strong-winds-thousands-of-acres-of-crops-damaged/","Athens Times","2026-07-23","powerful gusts combined with sudden, intense hail devastated crops including cotton, maize, vetch, seed production fields, vegetables, beans, and nut trees — especially walnut orchards.","weather_explicit"),
R("j058","NG","Lagos, Rivers, Niger State","mixed_grains","2026","flood","farmer_livelihood",False,None,None,None,"down",None,"2026-07","Nigerian flooding sweeps away three of seven sections of a Lagos vegetable farm; corn harvest cut from 1.2t to 650kg","https://www.vanguardngr.com/2026/07/farmers-in-tale-of-woes-over-flooding/","Vanguard (Nigeria)","2026-07-25","about three out of the seven sections of the farm had been swept away by the flood","weather_explicit"),
R("j059","US","Kendall County, Texas Hill Country","livestock","2026","flood","farmer_livelihood",False,None,None,None,"down",None,"2026-07","Texas Hill Country flash floods wash out fences and water gaps; one rancher loses 180 round bales","https://texasfarmbureau.org/ranchers-begin-recovery-after-another-round-of-devastating-floods/","Texas Farm Bureau","2026-07-23","All of the creeks were up this time.","weather_explicit"),
R("j060","RU","Russia and Ukraine","winter_wheat","2026/27","favourable","yield",False,None,None,None,"up",None,"2026-07","POSITIVE: July WASDE raises Russian and Ukrainian wheat on continued favourable winter wheat conditions","https://esmis.nal.usda.gov/sites/default/release-files/795974/wasde0726.pdf","USDA WAOB","2026-07-10","Production is raised for Russia and Ukraine on continued favorable conditions for their winter wheat crops.","weather_explicit"),
R("j061","FR","France","wheat","2026/27","heat","yield",False,None,None,None,"down","lowest in more than three decades","2026-07","July WASDE: record heat cuts French wheat to potentially the lowest in more than three decades","https://esmis.nal.usda.gov/sites/default/release-files/795974/wasde0726.pdf","USDA WAOB","2026-07-10","record heat reduces yield prospects. If realized, production for France would be the lowest in more than three decades.","weather_explicit"),
]

AUG = [
R("a001","GB","United Kingdom","mixed_grains","2026 harvest","drought","yield",True,"production",19.5,"million tonnes","down","worst on record since 1984; vs 21.4-22.0 Mt earlier forecasts","2026-08","UK cereals and oilseeds harvest projected at 19.5 Mt — the worst since records began in 1984","https://eciu.net/media/press-releases/uk-harvest-on-track-for-historic-lows-after-drought-and-heatwaves-desiccate-crops-new-analysis","ECIU","2026-08-05","the UK cereal and oilseeds harvest would be 19.5million tonnes, surpassing 2020 as the worst harvest on record since detailed records began in 1984","weather_explicit",4),
R("a002","GB","United Kingdom","mixed_grains","2026 harvest","drought","farmer_livelihood",True,"revenue",-390,"GBP million","down","range £293m-£390m","2026-08","Drought could cost UK arable farmers £293m-£390m in lost revenue, with 2.5 Mt off potential yield","https://www.fwi.co.uk/news/weather/drought-could-cost-arable-farmers-390m-in-lost-revenue","Farmers Weekly","2026-08-05","a loss of potential revenue of between £293m and £390m due to the drought","weather_explicit",4),
R("a003","GB","United Kingdom","wheat","2026 harvest","drought","yield",True,"yield",6.8,"t/ha","down","ten-year average of 7.9 t/ha","2026-07-27","UK wheat yield at 6.8 t/ha against a ten-year average of 7.9 t/ha, with 54% of the crop cut","https://www.farminguk.com/news/heat-and-drought-put-uk-on-course-for-worst-harvest-since-1984_68932.html","FarmingUK","2026-08-05","At the time, 54% of the wheat crop had been harvested, with the average yield estimated at 6.8 tonnes per hectare against a ten-year average of 7.9 tonnes.","weather_explicit",3),
R("a004","GB","United Kingdom","oilseed_rape","2026 harvest","favourable","yield",True,"yield",3.9,"t/ha","up","ten-year average of 3.3 t/ha","2026-07-27","POSITIVE: UK winter oilseed rape at 3.9 t/ha against a ten-year average of 3.3 t/ha","https://www.farminguk.com/news/heat-and-drought-put-uk-on-course-for-worst-harvest-since-1984_68932.html","FarmingUK","2026-08-05","Winter oilseed rape was performing more strongly, with an estimated yield of 3.9 tonnes per hectare compared with a ten-year average of 3.3 tonnes.","weather_explicit"),
R("a005","GB","England","potato","2026","heat","price_market",True,"spot_price",40,"% change","up","prior price level","2026-08","UK wholesale potato prices up more than 40% as heat and drought stunt tuber development","https://www.grocerygazette.co.uk/2026/08/04/uk-potato-crop-faces-heatwave-squeeze-as-wholesale-prices-surge-40/","Grocery Gazette","2026-08-04","Wholesale potato prices have already risen by more than 40 per cent","weather_explicit",3,["GB Potatoes","3Ms","Marks & Spencer","Aldi"]),
R("a006","GB","England","field_veg","2026","drought","price_market",True,"spot_price",60,"% change","up","normal wholesale price","2026-08","UK turns to imports: tomatoes up 60%, iceberg lettuce 90%, potatoes 40%; broccoli yields halved","https://www.aol.co.uk/articles/worst-ve-known-uk-turns-110052000.html","The Guardian","2026-08-02","The wholesale price of tomatoes is up by more than 60%, iceberg lettuce by 90% and potatoes by more than 40%","weather_explicit",0,["Riviera Produce","Nationwide Produce","Fen Peas"]),
R("a007","GB","England","potato","2026","drought","farmer_livelihood",True,"reservoir_fill",75.3,"%","down","7.4 points below seasonal average","2026-08","England reservoir storage at 75.3% with 1,353 restrictions on agricultural abstraction","https://www.grocerygazette.co.uk/2026/08/04/uk-potato-crop-faces-heatwave-squeeze-as-wholesale-prices-surge-40/","Grocery Gazette","2026-08-04","reservoir storage had fallen to 75.3 per cent, around 7.4 percentage points below the seasonal average","weather_explicit"),
R("a008","GB","East Anglia","potato","2026","heat","farmer_livelihood",False,None,None,None,"down",None,"2026-08","East Anglian grower group 3Ms says irrigation is failing to offset heat — potatoes are not bulking","https://www.grocerygazette.co.uk/2026/08/04/uk-potato-crop-faces-heatwave-squeeze-as-wholesale-prices-surge-40/","Grocery Gazette","2026-08-04","We've been chucking water on them, but in this heat they're not growing.","weather_explicit",0,["3Ms"]),
R("a009","GB","Norfolk","spring_barley","2026 harvest","drought","yield",True,"yield",-30,"%","down","normal yield","2026-08","Dewing Grain reports Norfolk spring barley yields 30% down and wheat 20% down","https://www.fwi.co.uk/arable/harvest/harvest-2026-scots-start-osr-and-poor-norfolk-spring-barley","Farmers Weekly","2026-08-04","Andrew Dewing, Dewing Grain managing director, reports spring barley yields are \"30% down\"","weather_explicit",0,["Dewing Grain"]),
R("a010","GB","Hertfordshire and Essex","wheat","2026 harvest","drought","yield",True,"yield",-17,"%","down","range 15-19% down","2026-08","Harlow Ag Merchants report wheat yields down 15-19% across Herts and Essex, though quality is strong","https://www.fwi.co.uk/arable/harvest/harvest-2026-scots-start-osr-and-poor-norfolk-spring-barley","Farmers Weekly","2026-08-04","Craig Martin, Harlow Ag Merchants, notes wheat yields down \"15-19%\"","weather_explicit",0,["Harlow Ag Merchants"]),
R("a011","GB","Lincolnshire (Skegness)","winter_wheat","2026 harvest","favourable","yield",True,"yield",12,"t/ha","up","GB average of 6.8 t/ha","2026-08","POSITIVE: Willow Farm near Skegness reports Palladium wheat at 12 t/ha on coastal silt soils","https://www.fwi.co.uk/arable/harvest/harvest-2026-promising-yields-in-yorks-and-on-lincs-coast","Farmers Weekly","2026-08-07","Palladium has been the standout performer at 12t/ha, with the remaining varieties achieving 10-11t/ha.","implied",2),
R("a012","GB","Gloucestershire (Staunton)","winter_wheat","2026 harvest","drought","yield",True,"yield",4.8,"t/ha","down","ten-year average of 7.9 t/ha","2026-08","The Hawthorns, Gloucestershire: Graham winter wheat yields just 4.8 t/ha","https://www.fwi.co.uk/arable/harvest/harvest-2026-promising-yields-in-yorks-and-on-lincs-coast","Farmers Weekly","2026-08-07","his 35ha of Graham winter wheat yielded just 4.8t/ha.","weather_explicit",2),
R("a013","GB","Scottish Borders","oilseed_rape","2026 harvest","favourable","yield",True,"yield",5.8,"t/ha","up","worst field 5.3 t/ha","2026-08","POSITIVE: Edrington Mains Farm, Scottish Borders reports OSR at 5.3-5.8 t/ha","https://www.fwi.co.uk/arable/harvest/harvest-2026-scots-start-osr-and-poor-norfolk-spring-barley","Farmers Weekly","2026-08-04","The best yield was 5.8t/ha, and the worst has been 5.3t/ha","implied"),
R("a014","GB","North Yorkshire","oilseed_rape","2026 harvest","favourable","yield",True,"yield",4.7,"t/ha","up","prior year 1.97 t/ha","2026-08","POSITIVE: Busby House Farm, North Yorkshire reports OSR at 4.7 t/ha, up from 1.97 t/ha last year","https://www.fwi.co.uk/arable/harvest/harvest-2026-promising-yields-in-yorks-and-on-lincs-coast","Farmers Weekly","2026-08-07","Last year we were about three weeks ahead and this year is the same","implied",0,None,"quote does not support the yield figure — needs re-verification"),
R("a015","GB","Great Britain","livestock","2026","drought","farmer_livelihood",True,"yield",-46,"%","down","2019-24 average grass growth","2026-07-31","ECIU: GB grass growth 46% below the 2019-24 average in the week to 31 July; season projected at 81% of average","https://www.farminguk.com/news/drought-sends-grass-growth-46-below-average_68946.html","FarmingUK / ECIU","2026-08-07","Analysis by the Energy and Climate Intelligence Unit (ECIU), using AHDB data, found growth in the week ending 31 July was 46% below the 2019-24 average.","weather_explicit"),
R("a016","GB","United Kingdom","dairy","2026","drought","farmer_livelihood",True,"deliveries",-18.5,"million litres","down","expected yields absent drought","2026-07","NFU Dairy Board: 18.5m litres wiped off UK milk yields as drought restricts grass growth","https://www.fwi.co.uk/news/weather/defra-under-pressure-to-ease-drought-impacts-on-food","Farmers Weekly","2026-08-03","It has severely restricted grass growth and diminished pasture quality, with 18.5m litres wiped off milk yields in recent weeks","weather_explicit",2),
R("a017","GB","Wales","livestock","2026","drought","farmer_livelihood",False,None,None,None,"down",None,"2026-08","Welsh farmers face a second consecutive winter of feed shortages as drought suppresses grass growth","https://nation.cymru/news/welsh-farmers-face-second-winter-of-feed-shortages-as-drought-hits-grass-growth/","Nation.Cymru","2026-08-07",None,"weather_explicit"),
R("a018","IE","South-East Ireland / Carlow","dairy","2026","drought","farmer_livelihood",True,"soil_moisture",100,"mm deficit","down","70-80mm rain needed to correct","2026-08","ICMSA reports 100mm soil moisture deficit; Carlow grass growth down to 13kg DM/ha/day","https://www.irishexaminer.com/farming/arid-41889007.html","Irish Examiner","2026-08-05","We are looking at 100mm of soil moisture deficit","weather_explicit"),
R("a019","IE","Ireland (Leinster and national)","dairy","2026","drought","yield",True,"yield",30,"kg DM/ha","down","normal summer growth rates","2026-07","Irish grass growth falls to 17kg DM/ha in Leinster, 30kg national average, forcing fodder budgeting","https://www.agriland.ie/farming-news/fodder-budgeting-through-another-week-of-drought/","Agriland","2026-08-01","average growth rates fell as low as 17kg of dry matter (DM)/ha in Leinster during the week, with a national average of 30kg of DM/ha.","weather_explicit"),
R("a020","GB","United Kingdom","wheat","2026/27","drought","price_market",True,"futures_price",196.5,"GBP/tonne","down","down £3.25/t on the week","2026-07-31","Nov-26 UK feed wheat futures fall to £196.50/t despite the drought-hit domestic harvest","https://ahdb.org.uk/news/arable-market-report-3-august-2026","AHDB","2026-08-03","Nov-26 UK feed wheat futures (green line with markers, Figure 1) dropped 3.25/t (-1.6%) last week to close Friday at £196.50/t.","weather_explicit"),
R("a021","FR","France","maize","2026","heat","yield",True,"condition_good_excellent",34,"%","down","38% previous week; 69% a year ago","2026-07-27","French maize falls to 34% good or excellent, against 69% a year earlier","https://ahdb.org.uk/news/arable-market-report-3-august-2026","AHDB","2026-08-03","As of 27 July, just 34% of the crop was rated in good or excellent condition, down from 38% a week earlier and well below the 69% recorded at the same point last year.","weather_explicit",2),
R("a022","FR","France","maize","2026 harvest","drought","yield",True,"production",9,"million tonnes","down","down 35% y/y; lowest since 1980","2026-08","French agriculture ministry forecasts a 9 Mt maize harvest, down 35% — the lowest since 1980","https://uk.news.yahoo.com/french-farmers-bracing-smallest-corn-144456939.html","RFI","2026-08-08","France's corn harvest is on pace this year for a 35 percent fall to nine million tons, a level last seen in 1980","weather_explicit"),
R("a023","PL","Poland","winter_wheat","2026","heat","yield",True,"production",11.6,"million tonnes","down","down 11% y/y","2026-08","Polish winter wheat forecast down 11% to 11.6 Mt after frost, heat, storms and hail","https://www.graincentral.com/markets/daily-market-wire-3-august-2026/","Grain Central","2026-08-03","Poland's winter wheat crop is forecast to fall 11 percent to 11.6Mt due to frost, heat, storms and hail.","weather_explicit",2),
R("a024","EU","EU-27","wheat","2026/27","drought","yield",True,"production",124.4,"million tonnes","down","previous Commission forecast","2026-08","European Commission cuts 2026/27 EU soft wheat forecast to 124.4 Mt","https://www.graincentral.com/markets/daily-market-wire-3-august-2026/","Grain Central","2026-08-03","EU wheat production prospects continue to deteriorate, with the European Commission cutting its 2026/27 soft wheat forecast to 124.4 million tonnes.","weather_explicit"),
R("a025","DE","Southern Germany","sugar","2026/27","drought","yield",True,"production",-33,"%","down","2025/26 output; lowest since 1990","2026-08","South German beet growers expect sugar output a third below last year — the lowest since reunification","https://www.cropli.io/sugar/2026/08/04/europe-s-official-sugar-forecasts-were-written-before-the-drought-reached-the-beet-crop","Cropli","2026-08-04","The Association of South German Sugar Beet Growers expects sugar output a third below last year","weather_explicit"),
R("a026","GB","United Kingdom","sugar","2026/27","drought","price_market",True,"spot_price",560,"EUR/tonne","down","previous month","2026-08","NFU Beet Brief: UK spot sugar around EUR 560/t as August rainfall becomes critical for the bulking crop","https://www.nfuonline.com/news/the-beet-brief-dry-weather-tests-european-crop-and-market-confidence/","NFU","2026-08-05","Current prices reflect caution rather than outright concern, with spot prices in the UK reported to be around €560/tonne, down on last month despite the continued weather concerns.","weather_explicit"),
R("a027","US","Midwest / Corn Belt","maize","2026","heat","yield",True,"condition_good_excellent",61,"%","down","63% previous week; 73% year earlier","2026-08-02","US corn falls to 61% good-to-excellent; very-poor-to-poor at 14%, highest for late July in three years","https://www.dtnpf.com/agriculture/web/ag/news/article/2026/08/03/usda-crop-progress-corn-rated-61-63","DTN/Progressive Farmer","2026-08-03","NASS estimated that 61% of the crop was in good-to-excellent condition, 2 percentage points below the previous week of 63%","weather_explicit",2),
R("a028","US","Northern Plains","spring_wheat","2026","favourable","yield",True,"condition_good_excellent",55,"%","up","53% previous week","2026-08-02","POSITIVE: US spring wheat improves to 55% good-to-excellent; Montana ratings jump 12 points","https://www.dtnpf.com/agriculture/web/ag/news/article/2026/08/03/usda-crop-progress-corn-rated-61-63","DTN/Progressive Farmer","2026-08-03","NASS estimated that 55% of the crop was in good-to-excellent condition nationwide, up 2 percentage points from the previous week's 53%","weather_explicit"),
R("a029","US","Northern Plains","spring_wheat","2026","drought","yield",True,"damaged_area",58,"% of acres in drought","up","up 33 points in two weeks","2026-08","US spring wheat acreage in drought surges 16 points to 58%; durum acres in drought jump to 49%","https://www.admis.com/ag-market-view-for-aug-6-2026-2/","ADM Investor Services","2026-08-06","US spring wheat acres in drought surged 16% to 58% (up 33% in 2 weeks). Durum acres in drought jumped 23% to 49%.","weather_explicit"),
R("a030","US","Iowa and Illinois","maize","2026","favourable","yield",True,"yield",184.8,"bu/acre","up","USDA July figure of 183","2026-08","POSITIVE: Midwest rain eases heat stress; StoneX raises US corn yield call to 184.8 bu/acre","https://www.graincentral.com/markets/daily-market-wire-6-august-2026/","Grain Central","2026-08-06","Rain moving through the Midwest, easing prior heat stress with Iowa and Illinois set for continued precipitation and cooler temps into next week, added to the yield-friendly tone.","weather_explicit",0,["StoneX"]),
R("a031","BR","Minas Gerais","coffee","2026","drought","price_market",True,"futures_price",331,"US cents/lb","up","supported by dry weather","2026-08","Arabica trades around 331c/lb, supported by dry weather in Minas Gerais threatening flowering","https://www.czapp.com/analyst-insights/futures-and-market-data-3rd-august-2026/","Czapp (Czarnikow)","2026-08-03","Arabica is trading around 331c/lb, supported by dry weather in Minas Gerais, Brazil's largest Arabica-growing region, which could affect flowering and future crop prospects.","weather_explicit"),
R("a032","IN","All-India","mixed_grains","kharif 2026","drought","food_security",True,"planted_area",78.738,"million hectares","down","83.619 million ha a year earlier","2026-07-31","India kharif sowing down nearly 39 lakh hectares to end-July amid a deficient monsoon","https://theprint.in/environment/india-kharif-39-lakh-hectares-rainfall-farmers/3007662/","ThePrint","2026-08-06","a total area of 787.38 lakh hectares was sown in the Kharif season this year till July compared to 836.19 lakh hectares sown during the same period last year.","weather_explicit"),
R("a033","EU","Czechia, France, Germany, Slovakia","maize","2026","heat","yield",False,None,None,None,"down",None,"2026-07-28","GEOGLAM: extreme heat and dryness cut EU maize yields, most notably in Czechia, France, Germany and Slovakia","https://www.cropmonitor.org/crop-monitor-for-amis-202608","GEOGLAM Crop Monitor","2026-08-06","In the EU, recent extremely hot and dry weather has cut yields across large parts of Europe, most notably in Czechia, France, Germany, and Slovakia.","weather_explicit"),
R("a034","TR","Türkiye","winter_wheat","2026","favourable","yield",False,None,None,None,"up",None,"2026-07-28","POSITIVE: GEOGLAM reports Türkiye's winter wheat harvest continuing with exceptional yields","https://www.cropmonitor.org/crop-monitor-for-amis-202608","GEOGLAM Crop Monitor","2026-08-06","In Türkiye, winter wheat harvest continues with exceptional yields.","weather_explicit"),
R("a035","DE","Rhine river corridor","mixed_grains","2026","drought","trade_policy",False,None,None,None,"down",None,"2026-08","Rhine water levels fall close to record lows, constraining European grain barge logistics","https://www.graincentral.com/markets/daily-market-wire-3-august-2026/","Grain Central","2026-08-03","Rhine River water levels fell close to record lows amid prolonged heat and dryness","weather_explicit"),
R("a036","US","Western Europe and the Americas","mixed_grains","2026","drought","company_corporate",False,None,None,None,"down",None,"2026-08","AGCO cites persistent European heat and drought behind a more measured farm machinery demand environment","https://www.fool.com/earnings/call-transcripts/2026/08/03/agco-agco-q2-2026-earnings-call-transcript/","AGCO (via Motley Fool)","2026-08-03","Weather continues to play a significant role as elevated temperatures and drought conditions persist across parts of Europe, along with ongoing weather variability in North and South America.","weather_explicit",0,["AGCO"]),
R("a037","GB","United Kingdom","mixed_grains","2026 harvest","drought","yield",True,"harvested_area",54,"% of area","up","earliest harvest in at least 20 years","2026-08","Reuters: Britain heads for worst cereal harvest in four decades; four of the five worst have come this decade","https://www.dailymaverick.co.za/article/2026-08-05-drought-hit-britain-heads-for-worst-cereal-harvest-in-four-decades/","Reuters","2026-08-05","Britain's cereal harvest is on track to be the worst since comparable records began in 1984","weather_explicit"),
]

for r in JUL: r["month"] = "2026-07"
for r in AUG: r["month"] = "2026-08"

rows = june + JUL + AUG

# ---------------------------------------------------------------- finalise
seen_claims = {}
for r in rows:
    r.setdefault("companies", [])
    r.setdefault("corroborations", [])
    r.setdefault("review_flag", None)
    if "source_badge" not in r:
        b, f = badge(r["url"], r["publisher"])
        r["source_badge"] = b
        if f and not r["review_flag"]: r["review_flag"] = f
    r["series_key"] = series_key(r)
    r["claim_key"] = claim_key(r)
    seen_claims.setdefault(r["claim_key"], r["id"])

by_month = collections.defaultdict(list)
for r in rows: by_month[r["month"]].append(r)
for m, rs in by_month.items():
    json.dump(rs, open(f"corpus/{m}.json", "w"), indent=1, ensure_ascii=False)

# series index — only series with >1 reading are chartable
series = collections.defaultdict(list)
for r in rows:
    if r["is_quantified"] and isinstance(r.get("metric_value"), (int, float)):
        series[r["series_key"]].append({"id": r["id"], "event_date": r.get("event_date"),
                                        "value": r["metric_value"], "unit": r["metric_unit"],
                                        "month": r["month"]})
chartable = {k: sorted(v, key=lambda x: x["event_date"] or "") for k, v in series.items() if len(v) > 1}
json.dump(chartable, open("index/series_index.json", "w"), indent=1)
json.dump({r["claim_key"]: {"id": r["id"], "corroboration_count": r.get("corroboration_count", 1)} for r in rows},
          open("index/claims_index.json", "w"), indent=1)
json.dump(rows, open("corpus/all.json", "w"), indent=1, ensure_ascii=False)

print("TOTAL ROWS:", len(rows))
for m in sorted(by_month): print(" ", m, len(by_month[m]))
print("quantified:", sum(1 for r in rows if r["is_quantified"]))
print("distinct series:", len(series), "| chartable (>1 reading):", len(chartable))
print("badges:", dict(collections.Counter(r["source_badge"] for r in rows)))
print("hazards:", dict(collections.Counter(r["hazard_type"] for r in rows)))
print("attribution:", dict(collections.Counter(r["attribution"] for r in rows)))
print("positive (up):", sum(1 for r in rows if r.get("direction") == "up"))
print("flagged:", sum(1 for r in rows if r.get("review_flag")))
print("\nTOP CHARTABLE SERIES:")
for k, v in sorted(chartable.items(), key=lambda x: -len(x[1]))[:14]:
    print(f"  {len(v)}x  {k}  ->  {[x['value'] for x in v]}")
missing = [r["id"] for r in rows if r["is_quantified"] and not r.get("verbatim_quote")]
print("\nquantified WITHOUT quote:", missing)
noev = [r["id"] for r in rows if r["is_quantified"] and not r.get("event_date")]
print("quantified WITHOUT event_date:", noev)
